---

# We need sudo for some of the Docker commands.
sudo: required

services: 
  - docker

env:
  - distro: ubuntu1604

script:
  # Download test script
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  
  # Add execute privileges to all script files that will be run
  - chmod +x ${PWD}/tests/test.sh

  # Run tests
  - ${PWD}/tests/test.sh