---

- name: SSL | Check if we've already generated a cert
  stat: 
    path: /etc/letsencrypt/live/{{ certbot_domain_name }}/cert.pem
  register: letsencrypt_cert

- name: SSL | Generate certs (first time)
  become: yes
  command: "{{ certbot_script }} certonly --standalone --noninteractive --agree-tos --email {{ certbot_email }} -d {{ certbot_domains | join(',') }}"
  when: not letsencrypt_cert.stat.exists

- name: SSL | Generate certs (subsequent times)
  become: yes
  command: certbot certonly --webroot -w {{ certbot_root_path }} -d {{ certbot_domains | join(',') }} --email {{ certbot_email }} --non-interactive --agree-tos
  when: letsencrypt_cert.stat.exists