---

- import_tasks: install.yml
  tags:
    - ssl
    - ssl_install

- import_tasks: certs.yml
  when: ssl_create_cert
  tags:
    - ssl
    - ssl_certs

- import_tasks: renew_cron.yml
  tags:
    - ssl
    - ssl_renew_cron